### PR TITLE
Will you continue to develop a version that supports MacOS？

### PR DESCRIPTION
**Pull request by dwz139**
Will you continue to develop a version that supports MacOS？

### CODE REVIEW

**Comment by dwz139** [comment]
Will you continue to develop a version that supports MacOS？ #16

**Comment by dwz139** [comment]
Will you continue to develop a version that supports MacOS？ #16

**Review by BazkieBumpercar — COMMENTED** [review]
Thanks for the effort but this repo is more of an archive thing and not supposed to be updated :)

**Comment by BazkieBumpercar** [comment]
> Will you continue to develop a version that supports MacOS？
I don't do any development on this anymore :) The fork from vi3itor is your best bet, I think!
Cheers, Bastiaan

**Pull request closed without merging**
